"""Template integrity guards for the Jinja2 admin portal.

The dashboard was once 6 hand-baked ~135KB HTML files generated by slicing a
dead monolith with a codegen script; that pipeline produced the double-nav bug
(v0.22.2) and shipped a duplicated 56KB script that made every page's JS a
SyntaxError. The portal is now Jinja2: base.html (one shell) + one child per
page + a single shared static/app.js. These tests render the real templates the
same way routes.py does and assert the invariants that failed before:

  1. rendered pages start with <!DOCTYPE html> (no python/module preamble),
  2. contain no python artifacts,
  3. carry exactly ONE nav bar, with the correct page active,
  4. carry the mobile hamburger/accordion and the auth-lock overlay,
  5. ship the shared JS exactly once, via /static/app.js (never inlined),
  6. init scripts are wrapped in an async IIFE (no top-level await),
  7. no page duplicates the mega-script (the old builder copied it 2x/page).
"""
import os
import re
import sys

import pytest
from jinja2 import Environment, FileSystemLoader

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, root)

TEMPLATES_DIR = os.path.join(root, "server", "templates")

PAGES = (
    "dashboard.html",
    "playlists.html",
    "widgets.html",
    "settings.html",
    "photos.html",
    "system.html",
)

ROUTES = {"/": "dashboard.html", "/playlists": "playlists.html", "/widgets": "widgets.html",
          "/settings": "settings.html", "/photos": "photos.html", "/system": "system.html"}

NAV_LINKS = ("/", "/playlists", "/widgets", "/settings", "/photos", "/system")

# python artifacts that leaked in v0.21.0 — must never appear in served html
PYTHON_MARKERS = (
    "import os\nimport sys",
    "from http.server import",
    "ACTIVE_SESSIONS",
    "SESSION_TTL_SECS",
    '"""',
)

# import the real nav definition so the rendered markup matches routes.py
from server.web.routes import NAV_LINKS as ROUTE_NAV_LINKS  # noqa: E402


def _render(name):
    env = Environment(loader=FileSystemLoader(TEMPLATES_DIR))
    # activate the link whose href maps to this page's route, exactly as routes.py does
    path_of = {v: k for k, v in ROUTES.items()}
    active_path = path_of.get(name)
    nav = [(href, label, href == active_path) for href, label in ROUTE_NAV_LINKS]
    return env.get_template(name).render(NAV_LINKS=nav)


def _load_raw(name):
    with open(os.path.join(TEMPLATES_DIR, name), "r", encoding="utf-8") as f:
        return f.read()


@pytest.mark.parametrize("name", PAGES)
def test_renders_and_starts_with_doctype(name):
    content = _render(name)
    assert content.startswith("<!DOCTYPE html>"), f"{name} missing <!DOCTYPE html> prologue"


@pytest.mark.parametrize("name", PAGES)
def test_no_python_artifacts(name):
    content = _load_raw(name)
    for marker in PYTHON_MARKERS:
        assert marker not in content, f"{name} contains python artifact: {marker!r}"


@pytest.mark.parametrize("name", PAGES)
def test_child_extends_base(name):
    raw = _load_raw(name)
    assert raw.startswith('{% extends "base.html" %}'), f"{name} should extend base.html"
    assert "{% block content %}" in raw and "{% block init %}" in raw


@pytest.mark.parametrize("name", PAGES)
def test_single_nav_bar(name):
    content = _render(name)
    assert content.count('id="section-tabs"') == 1, f"{name} must have exactly one nav bar"


@pytest.mark.parametrize("name", PAGES)
def test_exactly_one_link_active(name):
    """The active class must appear exactly once per nav (desktop + mobile)
    and only on the link whose href maps to this page's route."""
    content = _render(name)
    active_cls = "bg-orange-600 text-white shadow-lg shadow-orange-600/30"
    path = [p for p, t in ROUTES.items() if t == name][0]
    # one active link per nav: desktop (#section-tabs) and mobile (#mobile-nav)
    desktop = re.search(r'id="section-tabs".*?(?=<div id="mobile-nav"|<!-- Auth Lock)', content, re.S).group(0)
    mobile = re.search(r'id="mobile-nav".*?(?=<!-- Auth Lock)', content, re.S).group(0)
    for where, seg in (("desktop", desktop), ("mobile", mobile)):
        active_links = [m for m in re.finditer(r'<a href="([^"]+)"[^>]*>.*?</a>', seg, re.S)
                        if active_cls in m.group(0)]
        assert len(active_links) == 1, f"{name} {where} nav: {len(active_links)} active links"
        assert active_links[0].group(1) == path, f"{name} {where} nav: wrong link is active"


@pytest.mark.parametrize("name", PAGES)
def test_init_wrapped_in_iife(name):
    content = _render(name)
    assert "await checkAuthStatus" in content, f"{name} missing auth init"
    assert re.search(r"<script>\s*\(async \(\) => \{", content), f"{name} init not wrapped in async IIFE"


@pytest.mark.parametrize("name", PAGES)
def test_mobile_nav_present(name):
    content = _render(name)
    assert 'id="mobile-nav"' in content, f"{name} missing mobile nav accordion"
    assert 'id="nav-toggle"' in content, f"{name} missing hamburger toggle"
    assert "md:hidden" in content, f"{name} mobile nav not hidden on desktop"


@pytest.mark.parametrize("name", PAGES)
def test_mega_script_served_once_via_static(name):
    """The 56KB shared app.js must be referenced exactly once via /static/app.js
    and never inlined into a page (the old builder shipped it twice per page)."""
    content = _render(name)
    assert content.count('src="/static/app.js"') == 1, f"{name} must reference /static/app.js exactly once"
    raw = _load_raw(name)
    for page in PAGES:
        if page == "base.html":
            continue
        assert "let currentConfig" not in _load_raw(page) or page == name, ""
    assert "currentConfig" not in _load_raw(name).replace("{% block init %}", ""), \
        f"{name} must not inline the shared script body"


@pytest.mark.parametrize("name", PAGES)
def test_no_duplicated_script_blocks(name):
    """Regression: the old builder emitted the same 56KB block twice per page."""
    content = _render(name)
    blocks = re.findall(r"<script(?![^>]*\bsrc)[^>]*>(.*?)</script>", content, re.S)
    big = [b for b in blocks if len(b) > 5000]
    assert not big, f"{name} inlines a large script block ({len(big[0])}B) — move it to /static/app.js"


@pytest.mark.parametrize("name", PAGES)
def test_auth_lock_overlay_present(name):
    content = _render(name)
    assert 'id="auth-lock"' in content, f"{name} missing auth-lock overlay"
    assert "showLoginModal()" in content, f"{name} auth-lock must open the login modal"


@pytest.mark.parametrize("name", PAGES)
def test_balanced_script_style_and_html_close(name):
    content = _render(name)
    for tag in ("script", "style", "header", "main", "body", "html"):
        opens = len(re.findall(rf"<{tag}[\s>]", content))
        closes = content.count(f"</{tag}>")
        assert opens == closes, f"{name}: unbalanced <{tag}> ({opens} open / {closes} close)"


def test_base_html_exists_and_is_single_shell():
    raw = _load_raw("base.html")
    for required in ('id="auth-lock"', 'id="section-tabs"', 'id="mobile-nav"',
                     "/static/app.js", "{% block content %}", "{% block init %}"):
        assert required in raw, f"base.html missing {required!r}"
    assert "{% for href, label, active in NAV_LINKS %}" in raw, "base.html must render nav links from context"


def test_no_codegen_pipeline_files():
    root_dir = os.path.dirname(root)
    for legacy in ("server/templates/build_pages.py",
                   "server/templates/.build_parts.json",
                   "server/app.py"):
        assert not os.path.exists(os.path.join(root_dir, legacy)), \
            f"{legacy} must stay deleted (replaced by Jinja2 templates)"
